name: lint - test - build

on:
  push:
    branches: [master, main, develop, feature/*]
  pull_request:
    branches: [master, main, develop, feature/*]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Build project
        run: bun run build

      - name: Check results
        run: |
          echo "✅ All checks passed successfully!"
          echo "🎉 Linting, testing, and building completed without errors."
